export enum BatchStatus {
  CREATED = 'CREATED',
  MANUFACTURING = 'MANUFACTURING',
  QC_PENDING = 'QC_PENDING',
  QC_APPROVED = 'QC_APPROVED',
  QA_REVIEW = 'QA_REVIEW',
  RELEASED = 'RELEASED',
  REJECTED = 'REJECTED',
}
