import { MigrationInterface, QueryRunner } from "typeorm";

export class Phase8Statutory1788405305251 implements MigrationInterface {
    name = 'Phase8Statutory1788405305251'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`tax_declarations\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`employeeId\` bigint NOT NULL, \`financialYear\` varchar(9) NOT NULL, \`regime\` enum ('OLD', 'NEW') NOT NULL DEFAULT 'NEW', \`deduction80C\` decimal(14,2) NOT NULL DEFAULT '0.00', \`deduction80D\` decimal(14,2) NOT NULL DEFAULT '0.00', \`deduction80CCD1B\` decimal(14,2) NOT NULL DEFAULT '0.00', \`hraRentPaid\` decimal(14,2) NOT NULL DEFAULT '0.00', \`homeLoanInterest\` decimal(14,2) NOT NULL DEFAULT '0.00', \`otherExemptAllowances\` decimal(14,2) NOT NULL DEFAULT '0.00', \`otherChapterVIA\` decimal(14,2) NOT NULL DEFAULT '0.00', \`metroCity\` tinyint NOT NULL DEFAULT 0, \`status\` enum ('DRAFT', 'SUBMITTED', 'LOCKED') NOT NULL DEFAULT 'DRAFT', \`submittedAt\` datetime NULL, \`lockedByUserId\` varchar(36) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`uq_tax_decl_employee_fy\` (\`employeeId\`, \`financialYear\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`statutory_configs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`financialYear\` varchar(9) NOT NULL, \`effectiveFrom\` date NOT NULL, \`pfWageCeiling\` decimal(14,2) NOT NULL DEFAULT '15000.00', \`pfEmployeeRate\` decimal(6,3) NOT NULL DEFAULT '12.000', \`pfEmployerRate\` decimal(6,3) NOT NULL DEFAULT '12.000', \`epsRate\` decimal(6,3) NOT NULL DEFAULT '8.333', \`epsWageCeiling\` decimal(14,2) NOT NULL DEFAULT '15000.00', \`edliRate\` decimal(6,3) NOT NULL DEFAULT '0.500', \`pfAdminRate\` decimal(6,3) NOT NULL DEFAULT '0.500', \`pfCapAtCeilingDefault\` tinyint NOT NULL DEFAULT 1, \`esiWageCeiling\` decimal(14,2) NOT NULL DEFAULT '21000.00', \`esiEmployeeRate\` decimal(6,3) NOT NULL DEFAULT '0.750', \`esiEmployerRate\` decimal(6,3) NOT NULL DEFAULT '3.250', \`stdDeductionOld\` decimal(14,2) NOT NULL DEFAULT '50000.00', \`stdDeductionNew\` decimal(14,2) NOT NULL DEFAULT '75000.00', \`cessRate\` decimal(6,3) NOT NULL DEFAULT '4.000', \`rebate87aOldLimit\` decimal(14,2) NOT NULL DEFAULT '500000.00', \`rebate87aNewLimit\` decimal(14,2) NOT NULL DEFAULT '700000.00', \`active\` tinyint NOT NULL DEFAULT 1, \`createdByUserId\` varchar(36) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`idx_statutory_configs_active\` (\`active\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`pt_slabs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`stateCode\` varchar(4) NOT NULL, \`stateName\` varchar(60) NOT NULL, \`effectiveFrom\` date NOT NULL, \`minGross\` decimal(14,2) NOT NULL DEFAULT '0.00', \`maxGross\` decimal(14,2) NULL, \`monthlyAmount\` decimal(14,2) NOT NULL DEFAULT '0.00', \`februaryAmount\` decimal(14,2) NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_pt_slabs_state_active\` (\`stateCode\`, \`active\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payslip_statutory\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`payslipId\` bigint NOT NULL, \`employeeId\` bigint NOT NULL, \`periodMonth\` varchar(7) NOT NULL, \`financialYear\` varchar(9) NOT NULL, \`pfWages\` decimal(14,2) NOT NULL DEFAULT '0.00', \`epfEmployee\` decimal(14,2) NOT NULL DEFAULT '0.00', \`epsEmployer\` decimal(14,2) NOT NULL DEFAULT '0.00', \`epfEmployer\` decimal(14,2) NOT NULL DEFAULT '0.00', \`edliEmployer\` decimal(14,2) NOT NULL DEFAULT '0.00', \`pfAdminEmployer\` decimal(14,2) NOT NULL DEFAULT '0.00', \`ncpDays\` decimal(5,2) NOT NULL DEFAULT '0.00', \`esiApplicable\` tinyint NOT NULL DEFAULT 0, \`esiWages\` decimal(14,2) NOT NULL DEFAULT '0.00', \`esiEmployee\` decimal(14,2) NOT NULL DEFAULT '0.00', \`esiEmployer\` decimal(14,2) NOT NULL DEFAULT '0.00', \`ptStateCode\` varchar(4) NULL, \`ptAmount\` decimal(14,2) NOT NULL DEFAULT '0.00', \`taxRegime\` enum ('OLD', 'NEW') NOT NULL DEFAULT 'NEW', \`projectedAnnualGross\` decimal(14,2) NOT NULL DEFAULT '0.00', \`projectedTaxableIncome\` decimal(14,2) NOT NULL DEFAULT '0.00', \`projectedAnnualTax\` decimal(14,2) NOT NULL DEFAULT '0.00', \`tdsThisMonth\` decimal(14,2) NOT NULL DEFAULT '0.00', \`tdsYtd\` decimal(14,2) NOT NULL DEFAULT '0.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_payslip_statutory_emp_fy\` (\`employeeId\`, \`financialYear\`), INDEX \`idx_payslip_statutory_period\` (\`periodMonth\`), UNIQUE INDEX \`uq_payslip_statutory_payslip\` (\`payslipId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`income_tax_slabs\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`regime\` enum ('OLD', 'NEW') NOT NULL, \`financialYear\` varchar(9) NOT NULL, \`effectiveFrom\` date NOT NULL, \`minAnnual\` decimal(14,2) NOT NULL DEFAULT '0.00', \`maxAnnual\` decimal(14,2) NULL, \`ratePercent\` decimal(6,3) NOT NULL DEFAULT '0.000', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_it_slabs_regime_fy\` (\`regime\`, \`financialYear\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employee_statutory_profiles\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`employeeId\` bigint NOT NULL, \`pfApplicable\` tinyint NOT NULL DEFAULT 1, \`pfUsesActualWage\` tinyint NOT NULL DEFAULT 0, \`esiApplicable\` tinyint NULL, \`ptStateCode\` varchar(4) NOT NULL DEFAULT 'MH', \`uanNumber\` varchar(30) NULL, \`pfAccountNumber\` varchar(40) NULL, \`esiIpNumber\` varchar(30) NULL, \`createdByUserId\` varchar(36) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`uq_emp_statutory_employee\` (\`employeeId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`payslips\` ADD \`employerContributions\` decimal(14,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`payslips\` ADD \`ctcMonthly\` decimal(14,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`payslips\` ADD \`tdsAmount\` decimal(14,2) NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`salary_components\` CHANGE \`type\` \`type\` enum ('EARNING', 'DEDUCTION', 'EMPLOYER_CONTRIBUTION') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payslip_lines\` CHANGE \`type\` \`type\` enum ('EARNING', 'DEDUCTION', 'EMPLOYER_CONTRIBUTION') NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`payslip_lines\` CHANGE \`type\` \`type\` enum ('EARNING', 'DEDUCTION') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`salary_components\` CHANGE \`type\` \`type\` enum ('EARNING', 'DEDUCTION') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payslips\` DROP COLUMN \`tdsAmount\``);
        await queryRunner.query(`ALTER TABLE \`payslips\` DROP COLUMN \`ctcMonthly\``);
        await queryRunner.query(`ALTER TABLE \`payslips\` DROP COLUMN \`employerContributions\``);
        await queryRunner.query(`DROP INDEX \`uq_emp_statutory_employee\` ON \`employee_statutory_profiles\``);
        await queryRunner.query(`DROP TABLE \`employee_statutory_profiles\``);
        await queryRunner.query(`DROP INDEX \`idx_it_slabs_regime_fy\` ON \`income_tax_slabs\``);
        await queryRunner.query(`DROP TABLE \`income_tax_slabs\``);
        await queryRunner.query(`DROP INDEX \`uq_payslip_statutory_payslip\` ON \`payslip_statutory\``);
        await queryRunner.query(`DROP INDEX \`idx_payslip_statutory_period\` ON \`payslip_statutory\``);
        await queryRunner.query(`DROP INDEX \`idx_payslip_statutory_emp_fy\` ON \`payslip_statutory\``);
        await queryRunner.query(`DROP TABLE \`payslip_statutory\``);
        await queryRunner.query(`DROP INDEX \`idx_pt_slabs_state_active\` ON \`pt_slabs\``);
        await queryRunner.query(`DROP TABLE \`pt_slabs\``);
        await queryRunner.query(`DROP INDEX \`idx_statutory_configs_active\` ON \`statutory_configs\``);
        await queryRunner.query(`DROP TABLE \`statutory_configs\``);
        await queryRunner.query(`DROP INDEX \`uq_tax_decl_employee_fy\` ON \`tax_declarations\``);
        await queryRunner.query(`DROP TABLE \`tax_declarations\``);
    }

}
